### ISSUE TITLE
Package maintenance question.

### ISSUE THREAD

**Issue by JounQin** [jkroso/eslint-plugin-jsx#4]
Hi, @jkroso .

First thanks very much for creating this plugin, but it seems that it's out of maintenance about almost 4 years.

My question here is, if you don't mind and don't want to maintain this package any more, would you like to transfer the ownership of npm package? It would be great to let it be reborn and benifit the community.

My apologize for any rude requests.

Best wishes.

**Comment by jkroso** [comment]
Yeah no problem. Just tell me what commands to run

**Comment by JounQin** [comment]
@jkroso 

```sh
npm owner add jounqin eslint-plugin-jsx
```

(Would you mind to transfer this repository at the same time?)

**Comment by JounQin** [comment]
Thanks @jkroso for your kindness!
